/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import model.Korisnik;
import model.Predstava;
import model.Repertoar;
import tableModel.TableModelRepertoar;

/**
 *
 * @author Ana
 */
public class MainForm extends javax.swing.JFrame {
    List<Repertoar> lista=Controller.getInstance().vratiListuRepertoara();
    Korisnik korisnik;
    /**
     * Creates new form MainForm
     */
    public MainForm(Korisnik k) {
        initComponents();
        popuniComboBox();
        jLabel2.setText(k.getIme()+" "+k.getPrezime());
              
        TableModelRepertoar tmr=new TableModelRepertoar(lista);
        jTableRepertoar.setModel(tmr);
       
        
      
        korisnik=k;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRepertoar = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMonth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonFiltriraj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonOcistiFilter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dobrodosli,");

        jTableRepertoar.setBackground(new java.awt.Color(236, 236, 236));
        jTableRepertoar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableRepertoar.setForeground(new java.awt.Color(28, 153, 153));
        jTableRepertoar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRepertoar.setGridColor(new java.awt.Color(225, 225, 225));
        jTableRepertoar.setRowHeight(30);
        jTableRepertoar.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jTableRepertoar);

        jButtonObrisi.setBackground(new java.awt.Color(204, 204, 204));
        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonDetalji.setBackground(new java.awt.Color(228, 228, 228));
        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(41, 107, 107));
        jLabel5.setText("Datum:");

        jLabel6.setText("/");

        jLabel7.setText("/");

        jLabel8.setForeground(new java.awt.Color(41, 107, 107));
        jLabel8.setText("Predstava:");

        jButtonFiltriraj.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFiltriraj.setText("Filtriraj");
        jButtonFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrirajActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(41, 107, 107));
        jLabel4.setText("Dan       Mesec   Godina");

        jButtonOcistiFilter.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOcistiFilter.setText("Ocisti filter");
        jButtonOcistiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcistiFilterActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Azuriraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(126, 199, 199));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 132, 132));
        jLabel3.setText("REPERTOAR");

        jMenu1.setText("Repertoar");

        jMenuItem1.setText("Dodaj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Predstave");

        jMenuItem4.setText("Prikazi sve predstave");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Dodaj novu predstavu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(5, 5, 5)
                                .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jButtonFiltriraj)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonOcistiFilter)))
                        .addContainerGap(982, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1010, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jButtonDetalji)
                        .addGap(188, 188, 188)
                        .addComponent(jButtonObrisi)
                        .addGap(176, 176, 176)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(653, 653, 653)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFiltriraj)
                            .addComponent(jButtonOcistiFilter)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButton1)
                    .addComponent(jButtonDetalji))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        
        int selektovano=jTableRepertoar.getSelectedRow();
        if(selektovano==-1){
            JOptionPane.showMessageDialog(this,"Morate da oznacite sta zelite da obrisete", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }else{
            Repertoar r=lista.get(selektovano);
            int odgovor=JOptionPane.showConfirmDialog(this, "Da li ste sigurni?","Potvrda",JOptionPane.YES_NO_OPTION);
             switch (odgovor) {
                    case JOptionPane.YES_OPTION:
                    JOptionPane.showMessageDialog(this,"Uspesno", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
        
                 Controller.getInstance().obrisiPredstavuURepertoaru(r);
                azurirajTabelu();
                    
                    break;
                    case JOptionPane.NO_OPTION:
                    break;
                }
        }
            
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        AddRepertoar ar=new AddRepertoar(this, true,null);
        ar.setVisible(true);
        azurirajTabelu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    
        AddPerformance ap=new AddPerformance(this, true,korisnik);
        ap.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ShowPerformances sp=new ShowPerformances(this, true, korisnik);
        sp.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButtonFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrirajActionPerformed
        if((jTextFieldDay.getText().trim().equals("") || jTextFieldMonth.getText().trim().equals("") || jTextFieldYear.getText().trim().equals("")) && jComboBox1.getSelectedItem()==null){
            azurirajTabelu();
            JOptionPane.showMessageDialog(this,"Morate uneti odgovarajuce parametre", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        else if((jTextFieldDay.getText().trim().equals("") || jTextFieldMonth.getText().trim().equals("") || jTextFieldYear.getText().trim().equals("")) && jComboBox1.getSelectedItem()!=null){
           Predstava p=(Predstava) jComboBox1.getSelectedItem();
            vratiFiltriranoSaPredstavom(p);
        }else if(!(jTextFieldDay.getText().trim().equals("") || jTextFieldMonth.getText().trim().equals("") || jTextFieldYear.getText().trim().equals("")) && jComboBox1.getSelectedItem()==null){
            String dan=jTextFieldDay.getText();
            String mesec=jTextFieldMonth.getText();
            String godina=jTextFieldYear.getText();
            String datum=dan+"."+mesec+"."+godina;
            if(!datum.matches("^(0?[1-9]|[12][0-9]|3[01])\\.(0?[1-9]|1[0-2])\\.(\\d+)$")){
                 JOptionPane.showMessageDialog(this,"Morate uneti datum u odgovarajucem formatu", "GRESKA", JOptionPane.ERROR_MESSAGE);
      
            }else{
                try {
                    vratiFiltriranoSaDatumom(datum);
                } catch (ParseException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            Predstava p=(Predstava) jComboBox1.getSelectedItem();
            //vratiFiltriranoSaPredstavom(p);
            String dan=jTextFieldDay.getText();
            String mesec=jTextFieldMonth.getText();
            String godina=jTextFieldYear.getText();
            String datum=dan+"."+mesec+"."+godina;
            if(!datum.matches("^(0?[1-9]|[12][0-9]|3[01])\\.(0?[1-9]|1[0-2])\\.(\\d+)$")){
                 JOptionPane.showMessageDialog(this,"Morate uneti datum u odgovarajucem formatu", "GRESKA", JOptionPane.ERROR_MESSAGE);
      
            }else{
                vratiFiltriranoOba(p,datum);
            }
        }



    }//GEN-LAST:event_jButtonFiltrirajActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int selektovano=jTableRepertoar.getSelectedRow();
        if(selektovano==-1){
            JOptionPane.showMessageDialog(this,"Morate da oznacite", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }else{
            Repertoar r=lista.get(selektovano);
           RepertoarDetails rd=new RepertoarDetails(this, true, r);
           rd.setVisible(true);
        }

    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    private void jButtonOcistiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcistiFilterActionPerformed
        jTextFieldDay.setText("");
        jTextFieldYear.setText("");
        jTextFieldMonth.setText("");
        jComboBox1.setSelectedItem(null);
        
        azurirajTabelu();
    }//GEN-LAST:event_jButtonOcistiFilterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selektovano=jTableRepertoar.getSelectedRow();
        if(selektovano==-1){
            JOptionPane.showMessageDialog(this,"Morate da oznacite", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }else{
            Repertoar r=lista.get(selektovano);
            FormUpdateRepertoar fur=new FormUpdateRepertoar(this, true, r);
            fur.setVisible(true);
            azurirajTabelu();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonFiltriraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOcistiFilter;
    private javax.swing.JComboBox<Predstava> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRepertoar;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables

    private void azurirajTabelu() {
       List<Repertoar> lista2=Controller.getInstance().vratiListuRepertoara();
         TableModelRepertoar tmr=new TableModelRepertoar(lista2);
        jTableRepertoar.setModel(tmr);
           

    }
    public void popuniComboBox(){
        List<Predstava> lista=Controller.getInstance().vratiListuPredstava();
        jComboBox1.addItem(null);
        for (Predstava predstava : lista) {
            jComboBox1.addItem(predstava);
        }
    }

    private void vratiFiltriranoSaPredstavom(Predstava p) {
         List<Repertoar> listaRep=Controller.getInstance().vratiListuRepertoaraOdgovarajucePredstave(p);
         TableModelRepertoar tmr=new TableModelRepertoar(listaRep);
        jTableRepertoar.setModel(tmr);

    }

    private void vratiFiltriranoSaDatumom(String datum) throws ParseException {
         List<Repertoar> listaRep=Controller.getInstance().vratiListuRepertoaraDatum(datum);
         TableModelRepertoar tmr=new TableModelRepertoar(listaRep);
        jTableRepertoar.setModel(tmr);

    }

    private void vratiFiltriranoOba(Predstava p, String datum) {
        HashMap<String, List<Object>> objekti=new HashMap<>();
        List<Object> lista=new ArrayList<>();
        lista.add(p);
        lista.add(datum);
        objekti.put("string", lista);
        List<Repertoar> listaRep=Controller.getInstance().vratiListuRepertoaraOba(objekti);
         TableModelRepertoar tmr=new TableModelRepertoar(listaRep);
        jTableRepertoar.setModel(tmr);

    }
}
