/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import model.Korisnik;
import model.Predstava;
import tableModel.TableModelPerformance;

/**
 *
 * @author Ana
 */
public class ShowPerformances extends javax.swing.JDialog {
    List<Predstava> listaPredstava=Controller.getInstance().vratiListuPredstava();
    private Locale currentLocale;
    private ResourceBundle messages;
    /**
     * Creates new form ShowPerformances
     */
    public ShowPerformances(java.awt.Frame parent, boolean modal,Korisnik k, Locale currentLocale) {
        super(parent, modal);
        initComponents();
        jTextField2.setText(k.getEmail());
        jTextField2.setEnabled(false);
        TableModelPerformance tmp=new TableModelPerformance(listaPredstava);
        jTable1.setModel(tmp);
        
        this.currentLocale = currentLocale;
        
        loadLanguage();
        updateTexts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Predstava:");

        jButton1.setText("Detalji");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selektovano=jTable1.getSelectedRow();
        if(selektovano==-1){
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                       JOptionPane.showMessageDialog(this,"Morate da oznacite", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must select a field", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen markieren", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
           
        }else{
            Predstava p=listaPredstava.get(selektovano);
            PerformanceDetails pd=new PerformanceDetails(this, true, p, currentLocale);
            pd.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
 private void azurirajTabelu() {
        List<Predstava> lista2=Controller.getInstance().vratiListuPredstava();
        TableModelPerformance tmp=new TableModelPerformance(lista2);
        jTable1.setModel(tmp);
        

    }
 private void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
        jButton1.setText(messages.getString("jButtonDetalji.text"));
        jLabel1.setText(messages.getString("jLabelPredstave.text"));
    }

}
