/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Glumac;
import model.GlumacUloga;
import model.Koreograf;
import model.Korisnik;
import model.Kostimograf;
import model.Reziser;
import model.Scenograf;
import model.Zanr;
import tableModel.TableModelGlumacUloga;
import tableModel.TableModelGlumci;

/**
 *
 * @author Ana
 */
public class AddPerformance2 extends javax.swing.JDialog {
    List<Glumac> listaGlumaca=Controller.getInstance().vratiListuGlumaca();
    List<GlumacUloga> listaGU=new ArrayList<>();
    Korisnik korisnik;
     String naziv;
    int trajanje;
    Zanr zanr;
    Reziser reziser;
    Koreograf koreograf1;
    Scenograf scenograf1;
    Kostimograf kostimograf1;
    List<String> uloge1;
    /**
     * Creates new form AddPerformance2
     */
    public AddPerformance2(AddPerformance parent, boolean modal, Korisnik k,String naz, int tr, Reziser rez, Zanr zan,Koreograf koreograf, Scenograf scenograf, Kostimograf kostimograf, List<String> uloge) {
        super(parent, modal);
        initComponents();
        popuniComboBox(uloge);
        jTextField2.setText(k.getEmail());
        jTextField2.setEnabled(false);
        TableModelGlumci tmg=new TableModelGlumci(listaGlumaca);
        jTable1.setModel(tmg);
        korisnik=k;
        TableModelGlumacUloga tmgu=new TableModelGlumacUloga(listaGU);
        jTableGlumacUloga.setModel(tmgu);
        naziv=naz;
        trajanje=tr;
        zanr=zan;
        reziser=rez;
        koreograf1=koreograf;
        scenograf1=scenograf;
        kostimograf1=kostimograf;
        uloge1=uloge;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUloge = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGlumacUloga = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Zavrsi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Uloge:");

        jLabel9.setText("Glumci:");

        jTableGlumacUloga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableGlumacUloga);

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addComponent(jComboBoxUloge, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxUloge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        TableModelGlumacUloga tmgu2=(TableModelGlumacUloga) jTableGlumacUloga.getModel();
        List<GlumacUloga> listaGlumacUl=tmgu2.getLista();
        if(listaGlumacUl.isEmpty()){
             JOptionPane.showMessageDialog(this,"Morate dodati uloge", "Greska", JOptionPane.ERROR_MESSAGE);
        }else if(listaGlumacUl.size()!=uloge1.size()){
           JOptionPane.showMessageDialog(this,"Morate dodati glumce za sve uloge", "Greska", JOptionPane.ERROR_MESSAGE); 
        }else{
            List<Glumac> glumci=new ArrayList<>();
            List<String> uloge=new ArrayList<>();
            for (GlumacUloga glumacUloga : listaGlumacUl) {
                glumci.add(glumacUloga.getGlumac());
                uloge.add(glumacUloga.getUloga());
            }
            Controller.getInstance().dodajPredstavu2(naziv, trajanje, zanr,reziser, scenograf1,koreograf1,kostimograf1,glumci,uloge,korisnik);
            JOptionPane.showMessageDialog(this,"Uspesno dodato", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
        }

       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String uloga=(String) jComboBoxUloge.getSelectedItem();
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Morate selektovati", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
          int index=jTable1.getSelectedRow();
          Glumac g=listaGlumaca.get(index);
          listaGU.add(new GlumacUloga(uloga, g));
          azurirajTabelu();
          jComboBoxUloge.removeItem(uloga);
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxUloge;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableGlumacUloga;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public void popuniComboBox(List<String> uloge){
        for (String string : uloge) {
            jComboBoxUloge.addItem(string);
        }
    }

    private void azurirajTabelu() {
        TableModelGlumacUloga tmgu=new TableModelGlumacUloga(listaGU);
        jTableGlumacUloga.setModel(tmgu);
    }


}
