/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Glumac;
import model.GlumacUloga;
import model.Koreograf;
import model.Korisnik;
import model.Kostimograf;
import model.Reziser;
import model.Scenograf;
import model.Zanr;
import tableModel.TableModelGlumacUloga;
import tableModel.TableModelGlumci;

/**
 *
 * @author Ana
 */
public class AddPerformance extends javax.swing.JDialog {
    List<Glumac> listaGlumaca=Controller.getInstance().vratiListuGlumaca();
    Korisnik korisnik;
    List<GlumacUloga> listaGlumacUloga=new ArrayList<>();
    /**
     * Creates new form AddPerformance
     */
    public AddPerformance(java.awt.Frame parent, boolean modal, Korisnik k) {
        super(parent, modal);
        initComponents();
        popuniComboBox();
        jTextField2.setText(k.getEmail());
        jTextField2.setEnabled(false);
      
        korisnik=k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2Naziv = new javax.swing.JTextField();
        jTextFieldTrajanje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxReziser = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxScenograf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxKostimograf = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxKoreograf = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDodajNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel3.setText("Trajanje(min):");

        jLabel5.setText("Zanr:");

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jLabel4.setText("Reziser:");

        jLabel6.setText("Scenograf:");

        jLabel7.setText("Kostimograf:");

        jLabel8.setText("Koreograf:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonDodajNovo.setText("Dodaj ulogu");
        jButtonDodajNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajNovoActionPerformed(evt);
            }
        });

        jLabel2.setText("Uloge:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jButtonDodaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonDodajNovo)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxKoreograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxKostimograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxScenograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextField2Naziv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2Naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBoxScenograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxKostimograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxReziser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxKoreograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDodajNovo)
                        .addGap(155, 155, 155)))
                .addComponent(jButtonDodaj)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        
        String naziv=jTextField2Naziv.getText();
        
        Zanr zanr= (Zanr) jComboBox1.getSelectedItem();
        Reziser reziser=(Reziser) jComboBoxReziser.getSelectedItem();
        Scenograf scenograf=(Scenograf) jComboBoxScenograf.getSelectedItem();
        Koreograf kor=(Koreograf) jComboBoxKoreograf.getSelectedItem();
        Kostimograf kom=(Kostimograf) jComboBoxKostimograf.getSelectedItem();
      
        if(naziv.trim().isEmpty() || jTextFieldTrajanje.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "Greska", JOptionPane.ERROR_MESSAGE);
        }else{
            int trajanje=Integer.parseInt(jTextFieldTrajanje.getText());
            
            TableModelGlumacUloga tmgu2=(TableModelGlumacUloga) jTable1.getModel();
            List<GlumacUloga> listaGlumacUl=tmgu2.getLista();
            if(listaGlumacUl.isEmpty()){
                JOptionPane.showMessageDialog(this,"Morate dodati uloge", "Greska", JOptionPane.ERROR_MESSAGE);
            }else{
                List<Glumac> glumci=new ArrayList<>();
                List<String> uloge=new ArrayList<>();
                for (GlumacUloga glumacUloga : listaGlumacUl) {
                    glumci.add(glumacUloga.getGlumac());
                    uloge.add(glumacUloga.getUloga());
            }
            Controller.getInstance().dodajPredstavu2(naziv, trajanje, zanr,reziser, scenograf,kor,kom,glumci,uloge,korisnik);
            JOptionPane.showMessageDialog(this,"Uspesno dodato", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
        }}
        
        
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonDodajNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajNovoActionPerformed

        AddPerformance2New ap2=new AddPerformance2New(this, true, listaGlumacUloga);
        ap2.setVisible(true);
        azurirajTabelu();
    }//GEN-LAST:event_jButtonDodajNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonDodajNovo;
    private javax.swing.JComboBox<Zanr> jComboBox1;
    private javax.swing.JComboBox<Koreograf> jComboBoxKoreograf;
    private javax.swing.JComboBox<Kostimograf> jComboBoxKostimograf;
    private javax.swing.JComboBox<Reziser> jComboBoxReziser;
    private javax.swing.JComboBox<Scenograf> jComboBoxScenograf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2Naziv;
    private javax.swing.JTextField jTextFieldTrajanje;
    // End of variables declaration//GEN-END:variables

 public void popuniComboBox(){
      Zanr[] lista=Zanr.values();
      for (Zanr zanr : lista) {
          jComboBox1.addItem(zanr);
      }
      List<Reziser> listaR=Controller.getInstance().vratiListuRezisera();
      for (Reziser reziser : listaR) {
         jComboBoxReziser.addItem(reziser);
     }
      List<Scenograf> listaS=Controller.getInstance().vratiListuScenografa();
      for (Scenograf scenograf : listaS) {
         jComboBoxScenograf.addItem(scenograf);
     }
     List<Kostimograf> listaK=Controller.getInstance().vratiListuKostimografa();
     for (Kostimograf kostimograf : listaK) {
         jComboBoxKostimograf.addItem(kostimograf);
     }
     List<Koreograf> listaKo=Controller.getInstance().vratiListuKoreografa();
     for (Koreograf koreograf : listaKo) {
         jComboBoxKoreograf.addItem(koreograf);
     }
     
  }
 public static List<String> getElementsFromComboBox(JComboBox<String> comboBox) {
        List<String> elementsList = new ArrayList<>();

        // Iteracija kroz sve elemente ComboBox-a
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            elementsList.add(comboBox.getItemAt(i));
        }

        return elementsList;
    }

    private void azurirajTabelu() {
        TableModelGlumacUloga tmgu=new TableModelGlumacUloga(listaGlumacUloga);
        jTable1.setModel(tmgu);
    }
}
