/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Predstava;
import model.Repertoar;

/**
 *
 * @author Ana
 */
public class AddRepertoar extends javax.swing.JDialog {
    List<Predstava> listaPredstava=Controller.getInstance().vratiListuPredstava();
    /**
     * Creates new form AddRepertoar
     */
    public AddRepertoar(java.awt.Frame parent, boolean modal,Repertoar r) {
        super(parent, modal);
        initComponents();
        popuniComboBox();
        if(r==null){
            jButtonUpdate.setVisible(false);
        }else{
            jButtonDodaj.setVisible(false);
            for (int i=0;i<listaPredstava.size();i++) {
                if(listaPredstava.get(i).getId()==r.getPredstava().getId()){
                    jComboBox1.setSelectedIndex(i);
                }
            }
            
            
            jComboBox1.setEnabled(false);
            jTextFieldSala.setText(r.getSala());
            
            //datum
            SimpleDateFormat dayFormat = new SimpleDateFormat("dd");
            SimpleDateFormat monthFormat = new SimpleDateFormat("MM");
            SimpleDateFormat yearFormat = new SimpleDateFormat("yyyy");
        
            String day = dayFormat.format(r.getDatum());
            String month = monthFormat.format(r.getDatum());
            String year = yearFormat.format(r.getDatum());
            jTextFieldDay.setText(day);
            jTextFieldMonth.setText(month);
            jTextFieldYear.setText(year);
            
            //vreme
            String[] vreme=r.getVreme().split(":");
            jTextFieldVreme1.setText(vreme[0]);
            jTextFieldVreme2.setText(vreme[1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSala = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMonth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldVreme1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldVreme2 = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Sala:");

        jLabel3.setText("Datum:");

        jLabel6.setText("/");

        jLabel7.setText("/");

        jLabel4.setText("Dan       Mesec   Godina");

        jLabel5.setText("Vreme:");

        jLabel8.setText(":");

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Azuriraj");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(5, 5, 5)
                                        .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldVreme1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel8)
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldVreme2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonDodaj))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldVreme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVreme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(55, 55, 55)
                .addComponent(jButtonDodaj)
                .addGap(36, 36, 36)
                .addComponent(jButtonUpdate)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        if(jTextFieldSala.getText().trim().equals("") || jTextFieldDay.getText().trim().equals("") || jTextFieldMonth.getText().trim().equals("") 
                || jTextFieldYear.getText().trim().equals("") || jTextFieldVreme1.getText().trim().equals("") || jTextFieldVreme2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Morate popuniti sva polja", "Greska", JOptionPane.ERROR_MESSAGE);
        }else{
            Predstava p=(Predstava) jComboBox1.getSelectedItem();
            String sala=jTextFieldSala.getText();
            String dan=jTextFieldDay.getText();
            String mesec=jTextFieldMonth.getText();
            String godina=jTextFieldYear.getText();
            String date=dan+"."+mesec+"."+godina;
            SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
            String sat=jTextFieldVreme1.getText();
            String minuti=jTextFieldVreme2.getText();
            String vreme=sat+":"+minuti;
            try {
                Date datum = sdf.parse(date);
                Controller.getInstance().ubaciRepertoar(p,sala,datum,vreme);
            } catch (ParseException ex) {
                Logger.getLogger(AddRepertoar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
             JOptionPane.showMessageDialog(this,"Uspesno dodato", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
             this.dispose();
        }

    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        Predstava p=(Predstava) jComboBox1.getSelectedItem();
            String sala=jTextFieldSala.getText();
            String dan=jTextFieldDay.getText();
            String mesec=jTextFieldMonth.getText();
            String godina=jTextFieldYear.getText();
            String date=dan+"."+mesec+"."+godina;
            SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy");
            String sat=jTextFieldVreme1.getText();
            String minuti=jTextFieldVreme2.getText();
            String vreme=sat+":"+minuti;
            try {
                Date datum = sdf.parse(date);
                Controller.getInstance().azurirajRepertoar(p,sala,datum,vreme);
            } catch (ParseException ex) {
                Logger.getLogger(AddRepertoar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        

        JOptionPane.showMessageDialog(this,"Uspesno azurirano", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<Predstava> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldSala;
    private javax.swing.JTextField jTextFieldVreme1;
    private javax.swing.JTextField jTextFieldVreme2;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables

    public void popuniComboBox(){
        List<Predstava> predstave=Controller.getInstance().vratiListuPredstava();
        for (Predstava predstava : predstave) {
            jComboBox1.addItem(predstava);
        }
    }


}



