/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Ana
 */
public class FormRegister extends javax.swing.JDialog {

    /**
     * Creates new form FornRegister
     */
    public FormRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        
         jTxtRegEmail.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                
                validate(e);
            }

            private void validate(DocumentEvent e) {
                try {
                    String text=e.getDocument().getText(0,e.getDocument().getLength());
                    if(text.contains("@")){
                        jLabelError.setText("");
                    }
                    else{
                        jLabelError.setText("Morate uneti znak @");
                    }
                } catch (BadLocationException ex) {
                    
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validate(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
            
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jTxtRegEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtRegNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtRegName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jTxtRegSurname = new javax.swing.JTextField();
        jTxtRegPassword = new javax.swing.JPasswordField();
        jLabelSurname = new javax.swing.JLabel();
        jTxtRegPassword1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jCheckBoxCond = new javax.swing.JCheckBox();
        jButtonPrikaziLozinku2 = new javax.swing.JButton();
        jButtonPrikaziLozinku1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Registracija");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muski", "Zenski" }));

        jLabel1.setText("Pol:");

        jLabel3.setText("Ponovite lozinku:");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Registruj se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelName.setText("Ime:");

        jLabelError.setForeground(new java.awt.Color(255, 51, 0));

        jLabelSurname.setText("Prezime:");

        jTxtRegPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRegPassword1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Broj telefona:");

        jLabelEmail.setText("Email:");

        jLabelPassword.setText("Lozinka:");

        jCheckBoxCond.setText("Prihvatam uslove koriscenja");

        jButtonPrikaziLozinku2.setText("Prikazi lozinku");
        jButtonPrikaziLozinku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziLozinku2ActionPerformed(evt);
            }
        });

        jButtonPrikaziLozinku1.setText("Prikazi lozinku");
        jButtonPrikaziLozinku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziLozinku1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPassword))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtRegEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(jTxtRegPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jTxtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtRegSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(202, 202, 202)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jCheckBoxCond, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtRegPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonPrikaziLozinku2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(535, Short.MAX_VALUE)
                    .addComponent(jButtonPrikaziLozinku1)
                    .addGap(103, 103, 103)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTxtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname)
                    .addComponent(jTxtRegSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail)))
                    .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jTxtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtRegPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrikaziLozinku2))
                .addGap(13, 13, 13)
                .addComponent(jCheckBoxCond)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(jButtonPrikaziLozinku1)
                    .addGap(195, 195, 195)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
        String email=jTxtRegEmail.getText();
        String password=String.valueOf(jTxtRegPassword.getPassword());
        String passwordProvera=String.valueOf(jTxtRegPassword1.getPassword());
        String pol=(String) jComboBoxGender.getSelectedItem();
        ArrayList<JTextField> textFields = new ArrayList<>();
        if(!proveripolja()){
          
            textFields.add(jTxtRegName);
            textFields.add(jTxtRegSurname);
            textFields.add(jTxtRegNumber);
            textFields.add(jTxtRegEmail);
            textFields.add(jTxtRegPassword);
            textFields.add(jTxtRegPassword1);
            validiranje(textFields);
             JOptionPane.showMessageDialog(this, "Niste popunili obavezna polja", "Greska", JOptionPane.ERROR_MESSAGE);
       }else if(!validacijaPodataka()){
             validiranje(textFields);
             
             JOptionPane.showMessageDialog(this, "Niste popunili na odgovarajuci nacin ", "Greska", JOptionPane.ERROR_MESSAGE);

       }
        
       
        else{
            validiranje(textFields);
            if(jCheckBoxCond.isSelected()==false){
                JOptionPane.showMessageDialog(this, "Niste prihvatili uslove koriscenja", "Greska", JOptionPane.ERROR_MESSAGE);

            }else{
                int response = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da su podaci tacni?", "Registracija pri kraju", JOptionPane.YES_NO_OPTION);
                switch (response) {
                    case JOptionPane.YES_OPTION:
                     String randomPass=Controller.getInstance().generateRandomPassword();
                     String mejl=jTxtRegEmail.getText();
                     Controller.getInstance().sendMail(email, randomPass);
                     JOptionPane.showMessageDialog(this, "Uspesno registrovani!");
                     //Controller.getInstance().ubaciKorisnika(ime, prezime, broj,email ,password,pol);
                    this.dispose();
                    break;
                    case JOptionPane.NO_OPTION:
                    break;
                }
            }
            
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTxtRegPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRegPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRegPassword1ActionPerformed

    private void jButtonPrikaziLozinku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziLozinku2ActionPerformed

        jTxtRegPassword1.setEchoChar((char)0);

    }//GEN-LAST:event_jButtonPrikaziLozinku2ActionPerformed

    private void jButtonPrikaziLozinku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziLozinku1ActionPerformed

        jTxtRegPassword.setEchoChar((char)0);

    }//GEN-LAST:event_jButtonPrikaziLozinku1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPrikaziLozinku1;
    private javax.swing.JButton jButtonPrikaziLozinku2;
    private javax.swing.JCheckBox jCheckBoxCond;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JTextField jTxtRegEmail;
    private javax.swing.JTextField jTxtRegName;
    private javax.swing.JTextField jTxtRegNumber;
    private javax.swing.JPasswordField jTxtRegPassword;
    private javax.swing.JPasswordField jTxtRegPassword1;
    private javax.swing.JTextField jTxtRegSurname;
    // End of variables declaration//GEN-END:variables

    private boolean proveripolja() {
        String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
        String email=jTxtRegEmail.getText();
        String password=jTxtRegPassword.getText();
        String pol=(String) jComboBoxGender.getSelectedItem();
        if(ime.trim().isEmpty() || prezime.trim().isEmpty() || broj.trim().isEmpty() || email.trim().isEmpty() || password.trim().isEmpty() || pol==null){
            return false;
        }
        
        return true;
    }
    private void validiranje(ArrayList<JTextField> textFields) {  
        Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);

        for (JTextField textField : textFields) {
            if (textField.getText().trim().isEmpty()) {
                textField.setBorder(redBorder); 
                textField.setBackground(new Color(254,129, 129));
            } else {
                textField.setBorder(UIManager.getBorder("TextField.border")); 
                textField.setBackground(Color.WHITE);
            }
        }
    }

    private boolean validacijaPodataka() {
         String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
        String email=jTxtRegEmail.getText();
        String password=String.valueOf(jTxtRegPassword.getPassword());
        
        
        if(!ime.matches("[a-zA-Z]+") || !prezime.matches("[a-zA-Z]+") || !email.matches("^[a-z0-9.]+@[a-z]{1,20}\\.[a-z]{2,6}$")){
            return false;
        }else if(ime.length()<2 || prezime.length()<2 || broj.length()<6){
            return false;
        }else{
            return true;
        }
        
        
    }
}
