/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
 

/**
 *
 * @author Ana
 */
public class FormRegister0 extends javax.swing.JDialog {

    /**
     * Creates new form FormRegister0
     */
    public FormRegister0(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        jTextField1.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                
                validate(e);
            }

            private void validate(DocumentEvent e) {
                try {
                    String text=e.getDocument().getText(0,e.getDocument().getLength());
                    if(text.contains("@")){
                        jLabelError.setText("");
                    }
                    else{
                        jLabelError.setText("Morate uneti znak @");
                    }
                } catch (BadLocationException ex) {
                    
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validate(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
            
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registracija");

        jLabel2.setText("Email:");

        jButton1.setText("Nastavi registraciju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email=jTextField1.getText();
        if(email.trim().isEmpty()){
            Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
            jTextField1.setBorder(redBorder); 
            jTextField1.setBackground(new Color(254,129, 129));
            JOptionPane.showMessageDialog(this,"Morate popuniti polje za unos mail-a","GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!email.matches("^[a-z0-9.]+@[a-z]+(\\.[a-z]{1,10})+$")){
            JOptionPane.showMessageDialog(this,"Morate uneti u odgovarajucem formatu","GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }
       if(postojiVecEmail(email)){
           JOptionPane.showMessageDialog(this,"Email vec postoji","GRESKA", JOptionPane.ERROR_MESSAGE);
           return;
       }
        String randomPass = Controller.getInstance().generateRandomPassword();
        Controller.getInstance().sendMail(email, randomPass);
        String odgovor=JOptionPane.showInputDialog(this, "Na email Vam je poslata privremena lozinka, unesite je kako biste nastavili sa registracijom", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
        if(randomPass.equals(odgovor)){
            FormRegister1 fr=new FormRegister1(FormRegister0.this, true, email);
            fr.setVisible(true);
            this.dispose();
        }else if(odgovor.isEmpty()){
            JOptionPane.showMessageDialog(this, "Niste popunili polje", "Greska", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }else{
             JOptionPane.showMessageDialog(this, "Netacno", "Greska", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private boolean postojiVecEmail(String email) {
        List<String> lista=Controller.getInstance().vratiEmailove();
        for (String string : lista) {
            if(string.equals(email)){
                return true;
            }
        }
        
        return false;
    }
}
