/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;

/**
 *
 * @author Ana
 */
public class FormRegister1 extends javax.swing.JDialog {
String emailKorisnika;
    /**
     * Creates new form FormRegister1
     */
    public FormRegister1(FormRegister0 parent, boolean modal, String email) {
        super(parent, modal);
        initComponents();
        
        emailKorisnika=email;
        jLabelEmail.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTxtRegSurname = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtRegNumber = new javax.swing.JTextField();
        jTxtRegName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTxtRegPassword = new javax.swing.JPasswordField();
        jTxtRegPassword1 = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jCheckBoxCond = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButtonPrikaziLozinku2 = new javax.swing.JButton();
        jButtonPrikaziLozinku1 = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registracija");

        jButton1.setText("Zavrsi registraciju");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelSurname.setText("Prezime:");

        jLabel4.setText("Broj telefona:");

        jLabelName.setText("Ime:");

        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muski", "Zenski" }));

        jLabel3.setText("Pol:");

        jLabelPassword.setText("Nova lozinka:");

        jCheckBoxCond.setText("Prihvatam uslove koriscenja");

        jLabel5.setText("Ponovite lozinku:");

        jButtonPrikaziLozinku2.setText("Prikazi lozinku");
        jButtonPrikaziLozinku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziLozinku2ActionPerformed(evt);
            }
        });

        jButtonPrikaziLozinku1.setText("Prikazi lozinku");
        jButtonPrikaziLozinku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziLozinku1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabelPassword)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtRegPassword1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtRegPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonPrikaziLozinku1)
                                        .addComponent(jButtonPrikaziLozinku2))))
                            .addComponent(jTxtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTxtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRegSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 279, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxCond, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTxtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSurname)
                    .addComponent(jTxtRegSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRegNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRegPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword)
                    .addComponent(jButtonPrikaziLozinku2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonPrikaziLozinku1))
                .addGap(67, 67, 67)
                .addComponent(jCheckBoxCond)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziLozinku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziLozinku2ActionPerformed

        jTxtRegPassword1.setEchoChar((char)0);
    }//GEN-LAST:event_jButtonPrikaziLozinku2ActionPerformed

    private void jButtonPrikaziLozinku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziLozinku1ActionPerformed

        jTxtRegPassword.setEchoChar((char)0);
    }//GEN-LAST:event_jButtonPrikaziLozinku1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
        
        String password=String.valueOf(jTxtRegPassword.getPassword());
        String passwordProvera=String.valueOf(jTxtRegPassword1.getPassword());
        String pol=(String) jComboBoxGender.getSelectedItem();
        ArrayList<JTextField> textFields = new ArrayList<>();
        if(!proveripolja()){
          
            textFields.add(jTxtRegName);
            textFields.add(jTxtRegSurname);
            textFields.add(jTxtRegNumber);
            
            textFields.add(jTxtRegPassword);
            textFields.add(jTxtRegPassword1);
            validiranje(textFields);
             JOptionPane.showMessageDialog(this, "Niste popunili obavezna polja", "Greska", JOptionPane.ERROR_MESSAGE);
       }else if(!validacijaPodataka()){
             validiranje(textFields);
             
             JOptionPane.showMessageDialog(this, "Niste popunili na odgovarajuci nacin ", "Greska", JOptionPane.ERROR_MESSAGE);

       }else if(!password.equals(passwordProvera)){
            JOptionPane.showMessageDialog(this, "Nisu Vam jednake sifre", "Greska", JOptionPane.ERROR_MESSAGE);

       }
        
       
        else{
            validiranje(textFields);
            if(jCheckBoxCond.isSelected()==false){
                JOptionPane.showMessageDialog(this, "Niste prihvatili uslove koriscenja", "Greska", JOptionPane.ERROR_MESSAGE);

            }else{
                int response = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da su podaci tacni?", "Registracija pri kraju", JOptionPane.YES_NO_OPTION);
                switch (response) {
                    case JOptionPane.YES_OPTION:
                    
                     JOptionPane.showMessageDialog(this, "Uspesno registrovani!");
                     Controller.getInstance().ubaciKorisnika(ime, prezime, broj,emailKorisnika ,password,pol);
                    this.dispose();
                    break;
                    case JOptionPane.NO_OPTION:
                    break;
                }
            }
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPrikaziLozinku1;
    private javax.swing.JButton jButtonPrikaziLozinku2;
    private javax.swing.JCheckBox jCheckBoxCond;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JTextField jTxtRegName;
    private javax.swing.JTextField jTxtRegNumber;
    private javax.swing.JPasswordField jTxtRegPassword;
    private javax.swing.JPasswordField jTxtRegPassword1;
    private javax.swing.JTextField jTxtRegSurname;
    // End of variables declaration//GEN-END:variables
 private boolean proveripolja() {
        String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
        String pass=String.valueOf(jTxtRegPassword.getPassword());
        String pass2=String.valueOf(jTxtRegPassword1.getPassword());
        String pol=(String) jComboBoxGender.getSelectedItem();
        if(ime.trim().isEmpty() || prezime.trim().isEmpty() || broj.trim().isEmpty() || pol==null || pass.trim().isEmpty() || pass2.trim().isEmpty()){
            return false;
        }
        
        return true;
    }
    private void validiranje(ArrayList<JTextField> textFields) {  
        Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);

        for (JTextField textField : textFields) {
            if (textField.getText().trim().isEmpty()) {
                textField.setBorder(redBorder); 
                textField.setBackground(new Color(254,129, 129));
            } else {
                textField.setBorder(UIManager.getBorder("TextField.border")); 
                textField.setBackground(Color.WHITE);
            }
        }
    }

    private boolean validacijaPodataka() {
         String ime=jTxtRegName.getText();
        String prezime=jTxtRegSurname.getText();
        String broj=jTxtRegNumber.getText();
       
        String pass=String.valueOf(jTxtRegPassword.getPassword());
        String pass2=String.valueOf(jTxtRegPassword1.getPassword());
        
        if(!ime.matches("[a-zA-Z]+") || !prezime.matches("[a-zA-Z]+")){
            return false;
        }else if(ime.length()<2 || prezime.length()<2 || broj.length()<6 || pass.length()<4 || pass2.length()<4){
            return false;
        }else{
            return true;
        }
        
        
    }
}
