/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Glumac;
import model.GlumacUloga;
import model.Koreograf;
import model.Korisnik;
import model.Kostimograf;
import model.Predstava;
import model.Reziser;
import model.Scenograf;
import model.Zanr;
import tableModel.TableModelGlumacUloga;
import tableModel.TableModelGlumci;

/**
 *
 * @author Ana
 */
public class AddPerformance extends javax.swing.JDialog {
    List<Glumac> listaGlumaca=Controller.getInstance().vratiListuGlumaca();
    Korisnik korisnik;
    List<GlumacUloga> listaGlumacUloga=new ArrayList<>();
     private Locale currentLocale;
    private ResourceBundle messages;
    /**
     * Creates new form AddPerformance
     */
    public AddPerformance(java.awt.Frame parent, boolean modal, Korisnik k,Locale currentLocale) {
        super(parent, modal);
        initComponents();
        popuniComboBox();
        jTextField2.setText(k.getEmail());
        jTextField2.setEnabled(false);
      
        korisnik=k;
        
        this.currentLocale = currentLocale;
        
        loadLanguage();
        updateTexts();
        azurirajTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1naz = new javax.swing.JLabel();
        jLabeltrajanje = new javax.swing.JLabel();
        jTextField2Naziv = new javax.swing.JTextField();
        jTextFieldTrajanje = new javax.swing.JTextField();
        jLabelZanr = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jLabelReziser = new javax.swing.JLabel();
        jComboBoxReziser = new javax.swing.JComboBox<>();
        jLabelScenograf = new javax.swing.JLabel();
        jComboBoxScenograf = new javax.swing.JComboBox<>();
        jLabelKostimograf = new javax.swing.JLabel();
        jComboBoxKostimograf = new javax.swing.JComboBox<>();
        jLabelKoreog = new javax.swing.JLabel();
        jComboBoxKoreograf = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDodajNovo = new javax.swing.JButton();
        jLabelUloge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1naz.setText("Naziv:");

        jLabeltrajanje.setText("Trajanje(min):");

        jLabelZanr.setText("Zanr:");

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jLabelReziser.setText("Reziser:");

        jLabelScenograf.setText("Scenograf:");

        jLabelKostimograf.setText("Kostimograf:");

        jLabelKoreog.setText("Koreograf:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonDodajNovo.setText("Dodaj ulogu");
        jButtonDodajNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajNovoActionPerformed(evt);
            }
        });

        jLabelUloge.setText("Uloge:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jButtonDodaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelReziser)
                            .addComponent(jLabelZanr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeltrajanje)
                            .addComponent(jLabelUloge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1naz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonDodajNovo)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxReziser, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelScenograf)
                            .addComponent(jLabelKostimograf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKoreog))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxKoreograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxKostimograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxScenograf, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTextField2Naziv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1naz, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2Naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabeltrajanje)
                                    .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelZanr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelScenograf)
                                    .addComponent(jComboBoxScenograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKostimograf)
                            .addComponent(jComboBoxKostimograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxReziser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelReziser)
                            .addComponent(jLabelKoreog)
                            .addComponent(jComboBoxKoreograf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUloge))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDodajNovo)
                        .addGap(155, 155, 155)))
                .addComponent(jButtonDodaj)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        
        String naziv=jTextField2Naziv.getText();
        
        Zanr zanr= (Zanr) jComboBox1.getSelectedItem();
        Reziser reziser=(Reziser) jComboBoxReziser.getSelectedItem();
        Scenograf scenograf=(Scenograf) jComboBoxScenograf.getSelectedItem();
        Koreograf kor=(Koreograf) jComboBoxKoreograf.getSelectedItem();
        Kostimograf kom=(Kostimograf) jComboBoxKostimograf.getSelectedItem();
      
        if(naziv.trim().isEmpty() || jTextFieldTrajanje.getText().trim().isEmpty()){
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                        JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must fill in all the fields", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen alle Felder ausfüllen", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
            }else{
            int trajanje=Integer.parseInt(jTextFieldTrajanje.getText());
            
            TableModelGlumacUloga tmgu2=(TableModelGlumacUloga) jTable1.getModel();
            List<GlumacUloga> listaGlumacUl=tmgu2.getLista();
            if(listaGlumacUl.isEmpty()){
                switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                       JOptionPane.showMessageDialog(this,"Morate dodati uloge", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must add roles", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen Rollen hinzufügen", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
                  }else{
                List<Glumac> glumci=new ArrayList<>();
                List<String> uloge=new ArrayList<>();
                for (GlumacUloga glumacUloga : listaGlumacUl) {
                    glumci.add(glumacUloga.getGlumac());
                    uloge.add(glumacUloga.getUloga());
            }
            Predstava predstava=new Predstava(855, naziv, reziser, scenograf, kor, kom, trajanje, zanr, korisnik);
            HashMap<String, List<Object>> objekti=new HashMap<>();
            List<Object> lista=new ArrayList<>();
            lista.add(predstava);
            lista.add(glumci);
            lista.add(uloge);
            objekti.put("string", lista);
            Controller.getInstance().dodajPredstavu2(objekti);
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                          JOptionPane.showMessageDialog(this,"Uspesno dodato", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "Successfully added", "Successfully", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Erfolgreich hinzugefügt", "Erfolgreich", JOptionPane.ERROR_MESSAGE);
                }
         
            this.dispose(); 
        }}
        
        
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonDodajNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajNovoActionPerformed

        AddPerformance2New ap2=new AddPerformance2New(this, true, listaGlumacUloga, currentLocale);
        ap2.setVisible(true);
        azurirajTabelu();
    }//GEN-LAST:event_jButtonDodajNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonDodajNovo;
    private javax.swing.JComboBox<Zanr> jComboBox1;
    private javax.swing.JComboBox<Koreograf> jComboBoxKoreograf;
    private javax.swing.JComboBox<Kostimograf> jComboBoxKostimograf;
    private javax.swing.JComboBox<Reziser> jComboBoxReziser;
    private javax.swing.JComboBox<Scenograf> jComboBoxScenograf;
    private javax.swing.JLabel jLabel1naz;
    private javax.swing.JLabel jLabelKoreog;
    private javax.swing.JLabel jLabelKostimograf;
    private javax.swing.JLabel jLabelReziser;
    private javax.swing.JLabel jLabelScenograf;
    private javax.swing.JLabel jLabelUloge;
    private javax.swing.JLabel jLabelZanr;
    private javax.swing.JLabel jLabeltrajanje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2Naziv;
    private javax.swing.JTextField jTextFieldTrajanje;
    // End of variables declaration//GEN-END:variables

 public void popuniComboBox(){
      Zanr[] lista=Zanr.values();
      for (Zanr zanr : lista) {
          jComboBox1.addItem(zanr);
      }
      List<Reziser> listaR=Controller.getInstance().vratiListuRezisera();
      for (Reziser reziser : listaR) {
         jComboBoxReziser.addItem(reziser);
     }
      List<Scenograf> listaS=Controller.getInstance().vratiListuScenografa();
      for (Scenograf scenograf : listaS) {
         jComboBoxScenograf.addItem(scenograf);
     }
     List<Kostimograf> listaK=Controller.getInstance().vratiListuKostimografa();
     for (Kostimograf kostimograf : listaK) {
         jComboBoxKostimograf.addItem(kostimograf);
     }
     List<Koreograf> listaKo=Controller.getInstance().vratiListuKoreografa();
     for (Koreograf koreograf : listaKo) {
         jComboBoxKoreograf.addItem(koreograf);
     }
     
  }
 public static List<String> getElementsFromComboBox(JComboBox<String> comboBox) {
        List<String> elementsList = new ArrayList<>();

        // Iteracija kroz sve elemente ComboBox-a
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            elementsList.add(comboBox.getItemAt(i));
        }

        return elementsList;
    }

    private void azurirajTabelu() {
        TableModelGlumacUloga tmgu=new TableModelGlumacUloga(listaGlumacUloga);
        jTable1.setModel(tmgu);
    }

    private void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
        jLabel1naz.setText(messages.getString("jLabelNaziv.text"));
        jLabelKoreog.setText(messages.getString("jLabelKoreograf.text"));
        jLabelKostimograf.setText(messages.getString("jLabelKostimograf.text"));
        jLabelReziser.setText(messages.getString("jLabelReziser.text"));
        jLabelScenograf.setText(messages.getString("jLabelScenograf.text"));
        jLabelUloge.setText(messages.getString("jLabelUloge.text"));
        jLabelZanr.setText(messages.getString("jLabelZanr.text"));
        jLabeltrajanje.setText(messages.getString("jLabelTrajanje.text"));
        
        jButtonDodaj.setText(messages.getString("jMenuItem1.text"));
        jButtonDodajNovo.setText(messages.getString("jButtonDodajNovo.text"));
    }
}
