/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import model.Glumac;
import model.Repertoar;

/**
 *
 * @author Ana
 */
public class AddUpdateActor extends javax.swing.JDialog {
    private Locale currentLocale;
    private ResourceBundle messages;
    Glumac glumac;
    /**
     * Creates new form AddUpdateActor
     */
    public AddUpdateActor(ShowActors parent, boolean modal, Locale currentLocale,Glumac glumac) {
        super(parent, modal);
        initComponents();
        this.currentLocale = currentLocale;
        loadLanguage();
        updateTexts();
        this.glumac=glumac;
        if(glumac==null){
            jButtonAzuriraj.setVisible(false);
        }else{
            jButtonDodaj.setVisible(false);
            jTextFieldjmbg.setVisible(false);
            jLabel2.setVisible(false);
            jTextFieldime.setText(glumac.getIme());
            jTextField2.setText(glumac.getPrezime());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonDodaj = new javax.swing.JButton();
        jButtonAzuriraj = new javax.swing.JButton();
        jTextFieldjmbg = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextFieldime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("JMBG:");

        jLabel3.setText("Prezime:");

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonAzuriraj.setText("Azuriraj");
        jButtonAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldime, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAzuriraj)
                            .addComponent(jButtonDodaj))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldjmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jButtonDodaj)
                .addGap(18, 18, 18)
                .addComponent(jButtonAzuriraj)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        String jmbg=jTextFieldjmbg.getText();
        String ime=jTextFieldime.getText();
        String prezime=jTextField2.getText();
        
         
        if(jmbg.trim().isEmpty() || ime.trim().isEmpty() || prezime.trim().isEmpty()){
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                        JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must fill in all the fields", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen alle Felder ausfüllen", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
            }else{
            long jmbg1=Long.parseLong(jmbg);
            Glumac g=new Glumac(jmbg1, ime, prezime);
            Controller.getInstance().dodajGlumca(g);
            
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                          JOptionPane.showMessageDialog(this,"Uspesno dodato", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "Successfully added", "Successfully", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Erfolgreich hinzugefügt", "Erfolgreich", JOptionPane.ERROR_MESSAGE);
                }
             this.dispose();
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAzurirajActionPerformed
         String ime=jTextFieldime.getText();
        String prezime=jTextField2.getText();
        
         
        if(ime.trim().isEmpty() || prezime.trim().isEmpty()){
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                        JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must fill in all the fields", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen alle Felder ausfüllen", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
            }else{
            Glumac g=new Glumac(glumac.getJmbg(), ime, prezime);
           
            
            HashMap<String, List<Object>> objekti=new HashMap<>();
            List<Object> lista=new ArrayList<>();
            lista.add(g);
            lista.add(glumac);
            objekti.put("string", lista);
            Controller.getInstance().azurirajGlumca(objekti);
             
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                          JOptionPane.showMessageDialog(this,"Uspesno", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "Successfully", "Successfully", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Erfolgreich", "Erfolgreich", JOptionPane.ERROR_MESSAGE);
                }
              this.dispose();
        }
        
    }//GEN-LAST:event_jButtonAzurirajActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAzuriraj;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldime;
    private javax.swing.JTextField jTextFieldjmbg;
    // End of variables declaration//GEN-END:variables
private void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
        jLabel1.setText(messages.getString("jLabelName.text"));
        jLabel3.setText(messages.getString("jLabelSurname.text"));
        jButtonAzuriraj.setText(messages.getString("jButtonAzuriraj.text"));
        jButtonDodaj.setText(messages.getString("jMenuItem1.text"));
        
    }
}
