/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Repertoar;
import operations.Operations;

/**
 *
 * @author Ana
 */
public class FormUpdateRepertoar extends javax.swing.JDialog {
    Repertoar r=new Repertoar();
    private Locale currentLocale;
    private ResourceBundle messages;
    /**
     * Creates new form FormUpdateRepertoar
     */
    public FormUpdateRepertoar(java.awt.Frame parent, boolean modal,Repertoar repertoar, Locale currentLocale) {
        super(parent, modal);
        initComponents();
        r=repertoar;
        jLabelPredstava.setText(r.getPredstava().getNaziv());
        jTextFieldSala.setText(r.getSala());
        
        Date date= r.getDatum();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date);
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        jTextFieldDay.setText(String.valueOf(day));
        int month = calendar.get(Calendar.MONTH) + 1; 
        jTextFieldMonth.setText(String.valueOf(month));
        int year = calendar.get(Calendar.YEAR);
        jTextFieldYear.setText(String.valueOf(year));
        
        String vreme1=r.getVreme();
        String vreme[]=vreme1.split(":");
        jTextFieldSat.setText(vreme[0]);
        jTextFieldMinuti.setText(vreme[1]);
         this.currentLocale = currentLocale;
        
        loadLanguage();
        updateTexts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPred = new javax.swing.JLabel();
        jTextFieldSala = new javax.swing.JTextField();
        jLabelPredstava = new javax.swing.JLabel();
        jLabelSala = new javax.swing.JLabel();
        jLabelDat = new javax.swing.JLabel();
        jLabelvreme = new javax.swing.JLabel();
        jTextFieldSat = new javax.swing.JTextField();
        jLabelDMG = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMonth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMinuti = new javax.swing.JTextField();
        jButtoSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPred.setText("Predstava:");

        jLabelSala.setText("Sala:");

        jLabelDat.setText("Datum:");

        jLabelvreme.setText("Vreme:");

        jLabelDMG.setText("Dan       Mesec   Godina");

        jLabel6.setText("/");

        jLabel7.setText("/");

        jLabel8.setText(":");

        jButtoSacuvaj.setText("Sacuvaj");
        jButtoSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPred)
                            .addComponent(jLabelSala, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDat)
                            .addComponent(jLabelvreme, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPredstava, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldSat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(5, 5, 5)
                                        .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtoSacuvaj)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSala)
                                .addGap(181, 181, 181))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabelDMG)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPred, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPredstava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSala)
                    .addComponent(jTextFieldSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabelDMG)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDat)
                    .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelvreme)
                    .addComponent(jTextFieldSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldMinuti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButtoSacuvaj)
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoSacuvajActionPerformed
        String sala=jTextFieldSala.getText();
        String dan=jTextFieldDay.getText();
        String mesec=jTextFieldMonth.getText();
        String godina=jTextFieldYear.getText();
        String sati=jTextFieldSat.getText();
        String minuti=jTextFieldMinuti.getText();
        String datum=dan+"."+mesec+"."+godina;
        
        if(sala.trim().isEmpty() || dan.trim().isEmpty() || mesec.trim().isEmpty() || godina.trim().isEmpty() || sati.trim().isEmpty() || minuti.trim().isEmpty()){
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                        JOptionPane.showMessageDialog(this, "Morate popuniti sva polja", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must fill in all the fields", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen alle Felder ausfüllen", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
        }else if(!datum.matches("^(0?[1-9]|[12][0-9]|3[01])\\.(0?[1-9]|1[0-2])\\.(\\d+)$")){
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                        JOptionPane.showMessageDialog(this,"Morate uneti datum u odgovarajucem obliku", "GRESKA", JOptionPane.ERROR_MESSAGE);    
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must enter the date in the correct format", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen das Datum im richtigen Format eingeben", "FEHLER", JOptionPane.ERROR_MESSAGE);
                }
             //}else if(sati.matches("^(?:-?\\d+)$|^(?:2[4-9]|[3-9]\\d|\\d{3,})$") || minuti.matches("^(?:-?\\d+)$|^(?:[6-9]\\d|\\d{3,})$")){
             //JOptionPane.showMessageDialog(this,"Morate uneti vreme u odgovarajucem formatu", "GRESKA", JOptionPane.ERROR_MESSAGE);    
        }else{
            SimpleDateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
            String vreme=sati+":"+minuti;
              java.util.Date utilDate;
            try {
                utilDate = formatter.parse(datum);
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            Repertoar repertoar=new Repertoar(r.getPredstava(), sqlDate, vreme, sala);
            
            HashMap<String, List<Object>> objekti=new HashMap<>();
            List<Object> lista=new ArrayList<>();
            lista.add(r);
            lista.add(repertoar);
            objekti.put("string", lista);
            Controller.getInstance().azurirajRepertoar(objekti);
            } catch (ParseException ex) {
                Logger.getLogger(FormUpdateRepertoar.class.getName()).log(Level.SEVERE, null, ex);
            }
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                          JOptionPane.showMessageDialog(this,"Uspesno", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "Successfully", "Successfully", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Erfolgreich", "Erfolgreich", JOptionPane.ERROR_MESSAGE);
                }
              this.dispose();
        }


    }//GEN-LAST:event_jButtoSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoSacuvaj;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDMG;
    private javax.swing.JLabel jLabelDat;
    private javax.swing.JLabel jLabelPred;
    private javax.swing.JLabel jLabelPredstava;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelvreme;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldMinuti;
    private javax.swing.JTextField jTextFieldMonth;
    private javax.swing.JTextField jTextFieldSala;
    private javax.swing.JTextField jTextFieldSat;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables

    private void loadLanguage() {
         try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
       jButtoSacuvaj.setText(messages.getString("sacuvaj.text"));
       jLabelDMG.setText(messages.getString("jLabelDMG.text"));
       jLabelDat.setText(messages.getString("jLabelDatum.text"));
       jLabelPred.setText(messages.getString("jLabelPredstava.text"));
       jLabelSala.setText(messages.getString("jLabelSala.text"));
       jLabelvreme.setText(messages.getString("jLabelVreme.text"));
    }
}
