/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.awt.Color;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import model.Korisnik;
 

/**
 *
 * @author Ana
 */
public class FormRegister0 extends javax.swing.JDialog {
private Locale currentLocale;
    private ResourceBundle messages;
    /**
     * Creates new form FormRegister0
     */
    public FormRegister0(java.awt.Frame parent, boolean modal, Locale currentLocale) {
        
        super(parent, modal);
        initComponents();
         this.currentLocale = currentLocale;
        
        loadLanguage();
        updateTexts();
        jTextField1.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                
                validate(e);
            }

            private void validate(DocumentEvent e) {
                try {
                    String text=e.getDocument().getText(0,e.getDocument().getLength());
                    if(text.contains("@")){
                        jLabelError.setText("");
                    }
                    else{
                        //jezik
                        switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                      jLabelError.setText("Morate uneti znak @");
                    case "engleski" ->
                       jLabelError.setText("You must enter a character @");
                    case "nemacki" ->
                        jLabelError.setText("Sie müssen ein Zeichen eingeben @");
            }
                        
                    }
                } catch (BadLocationException ex) {
                    
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validate(e);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
            
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelReg = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jButtonNastaviReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelReg.setText("Registracija");

        jLabelEmail.setText("Email:");

        jButtonNastaviReg.setText("Nastavi registraciju");
        jButtonNastaviReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNastaviRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabelReg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonNastaviReg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelReg)
                .addGap(7, 7, 7)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(115, 115, 115)
                .addComponent(jButtonNastaviReg)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNastaviRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNastaviRegActionPerformed
        String email=jTextField1.getText();
        if(email.trim().isEmpty()){
            Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
            jTextField1.setBorder(redBorder); 
            jTextField1.setBackground(new Color(254,129, 129));
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                      JOptionPane.showMessageDialog(this,"Morate popuniti polje za unos mail-a","GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must fill in the email input field", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen das Eingabefeld für E-Mails ausfüllen", "FEHLER", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }
        if(!email.matches("^[a-z0-9.]+@[a-z]+(\\.[a-z]{1,10})+$")){
             switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                      JOptionPane.showMessageDialog(this,"Morate uneti u odgovarajucem formatu", "GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "You must enter in the appropriate format", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "Sie müssen im entsprechenden Format eingeben", "FEHLER", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }
       if(postojiVecEmail(email)){
            switch (currentLocale.getLanguage()) {
                    case "srpski" ->
                      JOptionPane.showMessageDialog(this,"Email vec postoji","GRESKA", JOptionPane.ERROR_MESSAGE);
                    case "engleski" ->
                       JOptionPane.showMessageDialog(this, "Email already exists", "ERROR", JOptionPane.ERROR_MESSAGE);
                    case "nemacki" ->
                        JOptionPane.showMessageDialog(this, "E-Mail existiert bereits", "FEHLER", JOptionPane.ERROR_MESSAGE);
            }
           
           return;
       }
        String randomPass = Controller.getInstance().generateRandomPassword();
        Controller.getInstance().sendMail(email, randomPass);
         String odgovor;
           if(currentLocale.getLanguage()=="srpski"){
                odgovor=JOptionPane.showInputDialog(this, "Na email Vam je poslata privremena lozinka, unesite je kako biste nastavili sa registracijom", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
                  if(odgovor==null){
                    return;
                    }
                    if(randomPass.equals(odgovor)){
                        FormRegister1 fr=new FormRegister1(FormRegister0.this, true, email,currentLocale);
                        fr.setVisible(true);
                        this.dispose();
                    }else if(odgovor.isEmpty()){
            
                       JOptionPane.showMessageDialog(this, "Niste popunili polje", "Greska", JOptionPane.ERROR_MESSAGE);
                    
           
                        this.dispose();
                    }else{
            
                       JOptionPane.showMessageDialog(this, "Netacno", "Greska", JOptionPane.ERROR_MESSAGE);
                 
             
             
                    this.dispose();
                    }

            
            }else if(currentLocale.getLanguage()=="engleski"){
                odgovor=JOptionPane.showInputDialog(this, "A temporary password has been sent to your email, please enter it to continue with the registration", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                if(odgovor==null){
                    return;
                    }
                    if(randomPass.equals(odgovor)){
                        FormRegister1 fr=new FormRegister1(FormRegister0.this, true, email,currentLocale);
                        fr.setVisible(true);
                        this.dispose();
                    }else if(odgovor.isEmpty()){
            
                     JOptionPane.showMessageDialog(this, "You have not filled in the field", "ERROR", JOptionPane.ERROR_MESSAGE);
           
                        this.dispose();
                    }else{
            
                       
                        JOptionPane.showMessageDialog(this, "Incorrect", "ERROR", JOptionPane.ERROR_MESSAGE);
             
                    this.dispose();
                    }

                
            }else if(currentLocale.getLanguage()=="nemacki"){
                odgovor=JOptionPane.showInputDialog(this, "Ein temporäres Passwort wurde an Ihre E-Mail-Adresse gesendet, bitte geben Sie es ein, um mit der Registrierung fortzufahren", "Bestätigung", JOptionPane.INFORMATION_MESSAGE);
                 if(odgovor==null){
                    return;
                    }
                    if(randomPass.equals(odgovor)){
                        FormRegister1 fr=new FormRegister1(FormRegister0.this, true, email,currentLocale);
                        fr.setVisible(true);
                        this.dispose();
                    }else if(odgovor.isEmpty()){
            
                      JOptionPane.showMessageDialog(this, "Sie haben das Feld nicht ausgefüllt", "FEHLER", JOptionPane.ERROR_MESSAGE);
                        this.dispose();
                    }else{
            
                       
                        JOptionPane.showMessageDialog(this, "Falsch", "FEHLER", JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                    }
            
            }
            
       
        
                       
            
       
    }//GEN-LAST:event_jButtonNastaviRegActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNastaviReg;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelReg;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private boolean postojiVecEmail(String email) {
        List<Korisnik> listaKorisnika=Controller.getInstance().vratiListuKorisnika();
        for (Korisnik korisnik : listaKorisnika) {
            if(korisnik.getEmail().equals(email)){
                return true;
            }
        }
        
        return false;
    }

    private void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
       jLabelEmail.setText(messages.getString("jTxtEmail.text"));
       jLabelReg.setText(messages.getString("jLabelReg.text"));
       jButtonNastaviReg.setText(messages.getString("nastaviReg.text"));
    }
}
