/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import controller.Controller;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Korisnik;

/**
 *
 * @author Ana
 */
public class LogIn extends javax.swing.JFrame {
    List<Korisnik> listaKorisnika=Controller.getInstance().vratiListuKorisnika();
    private Locale currentLocale;
    private ResourceBundle messages;
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        currentLocale = new Locale("srpski");
        loadLanguage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabelPrijava = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jButtonLogIn = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSifra = new javax.swing.JLabel();
        jLabelAkoNemate = new javax.swing.JLabel();
        jLabelReg = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jButtonPrikaziLozinku = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPrijava.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrijava.setForeground(new java.awt.Color(51, 51, 255));
        jLabelPrijava.setText("Prijava za registrovane korisnike");

        jTxtEmail.setText("ana.s@gmail.com");
        jTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailActionPerformed(evt);
            }
        });

        jButtonLogIn.setBackground(new java.awt.Color(51, 153, 255));
        jButtonLogIn.setText("Prijava");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelEmail.setText("Email:");

        jLabelSifra.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelSifra.setText("Sifra:");

        jLabelAkoNemate.setText("Ako nemate nalog:");

        jLabelReg.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabelReg.setForeground(new java.awt.Color(0, 51, 255));
        jLabelReg.setText("Registrujte se...");
        jLabelReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegMouseClicked(evt);
            }
        });

        jTxtPassword.setText("ana");

        jButtonPrikaziLozinku.setText("Prikazi lozinku");
        jButtonPrikaziLozinku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziLozinkuActionPerformed(evt);
            }
        });

        jMenu3.setText("Jezik");

        jMenuItem13.setText("Srpski jezik");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem23.setText("Engleski jezik");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuItem33.setText("Nemacki jezik");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem33);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabelPrijava)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAkoNemate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReg)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPrikaziLozinku)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSifra)
                    .addComponent(jButtonPrikaziLozinku))
                .addGap(54, 54, 54)
                .addComponent(jButtonLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAkoNemate)
                    .addComponent(jLabelReg))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
         List<Korisnik> listaKorisnika2=Controller.getInstance().vratiListuKorisnika();
        String email=jTxtEmail.getText();
        String pass=String.valueOf(jTxtPassword.getPassword());
        
        for (Korisnik korisnik : listaKorisnika2) {
            if(korisnik.getEmail().equals(email) && korisnik.getPassword().equals(pass)){
                MainForm enterForm=new MainForm(korisnik, currentLocale);
                enterForm.setVisible(true);
               
                enterForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
              
                this.dispose();
                
                return;
            }
        }
            
        JOptionPane.showMessageDialog(this, "Netacan email ili lozinka, pokusajte ponovo", "Greska", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_jButtonLogInActionPerformed

    private void jLabelRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegMouseClicked
        
                FormRegister0 formRegister= new FormRegister0(this, true,currentLocale);
                formRegister.setLocationRelativeTo(null);
                formRegister.setVisible(true);
                
                
    }//GEN-LAST:event_jLabelRegMouseClicked

    private void jButtonPrikaziLozinkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziLozinkuActionPerformed

        
        jTxtPassword.setEchoChar((char)0);

    }//GEN-LAST:event_jButtonPrikaziLozinkuActionPerformed

    private void jTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        currentLocale = new Locale("srpski");
        loadLanguage();
        updateTexts();        
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        currentLocale = new Locale("engleski");
        loadLanguage();
        updateTexts(); 
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        currentLocale = new Locale("nemacki");
        loadLanguage();
        updateTexts(); 

    }//GEN-LAST:event_jMenuItem33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
  public Korisnik vratiUlogovanogKorisnika(){
        String email=jTxtEmail.getText();
        String pass=String.valueOf(jTxtPassword.getPassword());
        
        for (Korisnik korisnik : listaKorisnika) {
            if(korisnik.getEmail().equals(email) && korisnik.getPassword().equals(pass)){
               return korisnik;
            }
        }
       return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JButton jButtonPrikaziLozinku;
    private javax.swing.JLabel jLabelAkoNemate;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPrijava;
    private javax.swing.JLabel jLabelReg;
    private javax.swing.JLabel jLabelSifra;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JPasswordField jTxtPassword;
    // End of variables declaration//GEN-END:variables

    private void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("prevod.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greska" + e.getMessage());
        }
    }

    private void updateTexts() {
        jMenu3.setText(messages.getString("jMenu3.text"));
        jMenuItem13.setText(messages.getString("jMenuItem13.text"));
        jMenuItem23.setText(messages.getString("jMenuItem23.text"));
        jMenuItem33.setText(messages.getString("jMenuItem33.text"));
        jLabelPrijava.setText(messages.getString("jLabelPrijava.text"));
        jLabelEmail.setText(messages.getString("jTxtEmail.text"));
        jLabelSifra.setText(messages.getString("jTxtPassword.text"));
        jLabelAkoNemate.setText(messages.getString("jLabelAkoNemate.text"));
        jLabelReg.setText(messages.getString("jLabelReg.text"));
        jButtonLogIn.setText(messages.getString("jButtonLogIn.text"));
        jButtonPrikaziLozinku.setText(messages.getString("jButtonPrikaziLozinku.text"));
    }
}
